const countryCurrencyLocales = [
    {
        country: "Aruba",
        code: "AW",
        currency: "AWG",
        locale: "en-AW",
    },
    {
        country: "Albania",
        code: "AL",
        currency: "ALL",
        locale: "en-AL",
    },
    {
        country: "United Arab Emirates",
        code: "AE",
        currency: "AED",
        locale: "en-AE",
    },
    {
        country: "Argentina",
        code: "AR",
        currency: "ARS",
        locale: "en-AR",
    },
    {
        country: "Armenia",
        code: "AM",
        currency: "AMD",
        locale: "en-AM",
    },
    {
        country: "Australia",
        code: "AU",
        currency: "AUD",
        locale: "en-AU",
    },
    {
        country: "Burundi",
        code: "BI",
        currency: "BIF",
        locale: "en-BI",
    },
    {
        country: "Bangladesh",
        code: "BD",
        currency: "BDT",
        locale: "en-BD",
    },
    {
        country: "Bahrain",
        code: "BH",
        currency: "BHD",
        locale: "en-BH",
    },
    {
        country: "Bahamas",
        code: "BS",
        currency: "BSD",
        locale: "en-BS",
    },
    {
        country: "Belize",
        code: "BZ",
        currency: "BZD",
        locale: "en-BZ",
    },
    {
        country: "Bermuda",
        code: "BM",
        currency: "BMD",
        locale: "en-BM",
    },
    {
        country: "Bolivia, Plurinational State of",
        code: "BO",
        currency: "BOB",
        locale: "en-BO",
    },
    {
        country: "Barbados",
        code: "BB",
        currency: "BBD",
        locale: "en-BB",
    },
    {
        country: "Brunei Darussalam",
        code: "BN",
        currency: "BND",
        locale: "en-BN",
    },
    {
        country: "Bhutan",
        code: "BT",
        currency: "BTN",
        locale: "en-BT",
    },
    {
        country: "Botswana",
        code: "BW",
        currency: "BWP",
        locale: "en-BW",
    },
    {
        country: "Canada",
        code: "CA",
        currency: "CAD",
        locale: "en-CA",
    },
    {
        country: "Switzerland",
        code: "CH",
        currency: "CHF",
        locale: "de-CH",
    },
    {
        country: "Chile",
        code: "CL",
        currency: "CLP",
        locale: "en-CL",
    },
    {
        country: "China",
        code: "CN",
        currency: "CNY",
        locale: "zh-CN",
    },
    {
        country: "Colombia",
        code: "CO",
        currency: "COP",
        locale: "en-CO",
    },
    {
        country: "Comoros",
        code: "KM",
        currency: "KMF",
        locale: "en-KM",
    },
    {
        country: "Cabo Verde",
        code: "CV",
        currency: "CVE",
        locale: "en-CV",
    },
    {
        country: "Costa Rica",
        code: "CR",
        currency: "CRC",
        locale: "en-CR",
    },
    {
        country: "Cuba",
        code: "CU",
        currency: "CUP",
        locale: "en-CU",
    },
    {
        country: "Cayman Islands",
        code: "KY",
        currency: "KYD",
        locale: "en-KY",
    },
    {
        country: "Czechia",
        code: "CZ",
        currency: "CZK",
        locale: "cs-CZ",
    },
    {
        country: "Djibouti",
        code: "DJ",
        currency: "DJF",
        locale: "en-DJ",
    },
    {
        country: "Denmark",
        code: "DK",
        currency: "DKK",
        locale: "da-DK",
    },
    {
        country: "Dominican Republic",
        code: "DO",
        currency: "DOP",
        locale: "en-DO",
    },
    {
        country: "Algeria",
        code: "DZ",
        currency: "DZD",
        locale: "en-DZ",
    },
    {
        country: "Egypt",
        code: "EG",
        currency: "EGP",
        locale: "en-EG",
    },
    {
        country: "Eritrea",
        code: "ER",
        currency: "ERN",
        locale: "en-ER",
    },
    {
        country: "Fiji",
        code: "FJ",
        currency: "FJD",
        locale: "en-FJ",
    },
    {
        country: "Falkland Islands (Malvinas)",
        code: "FK",
        currency: "FKP",
        locale: "en-FK",
    },
    {
        country: "United Kingdom",
        code: "GB",
        currency: "GBP",
        locale: "en-GB",
    },
    {
        country: "Gibraltar",
        code: "GI",
        currency: "GIP",
        locale: "en-GI",
    },
    {
        country: "Guinea",
        code: "GN",
        currency: "GNF",
        locale: "en-GN",
    },
    {
        country: "Gambia",
        code: "GM",
        currency: "GMD",
        locale: "en-GM",
    },
    {
        country: "Guatemala",
        code: "GT",
        currency: "GTQ",
        locale: "en-GT",
    },
    {
        country: "Guyana",
        code: "GY",
        currency: "GYD",
        locale: "en-GY",
    },
    {
        country: "Hong Kong",
        code: "HK",
        currency: "HKD",
        locale: "en-HK",
    },
    {
        country: "Honduras",
        code: "HN",
        currency: "HNL",
        locale: "en-HN",
    },
    {
        country: "Croatia",
        code: "HR",
        currency: "HRK",
        locale: "en-HR",
    },
    {
        country: "Haiti",
        code: "HT",
        currency: "HTG",
        locale: "en-HT",
    },
    {
        country: "Hungary",
        code: "HU",
        currency: "HUF",
        locale: "hu-HU",
    },
    {
        country: "Indonesia",
        code: "ID",
        currency: "IDR",
        locale: "id-ID",
    },
    {
        country: "India",
        code: "IN",
        currency: "INR",
        locale: "hi-IN",
    },
    {
        country: "Iran, Islamic Republic of",
        code: "IR",
        currency: "IRR",
        locale: "en-IR",
    },
    {
        country: "Iraq",
        code: "IQ",
        currency: "IQD",
        locale: "en-IQ",
    },
    {
        country: "Iceland",
        code: "IS",
        currency: "ISK",
        locale: "en-IS",
    },
    {
        country: "Israel",
        code: "IL",
        currency: "ILS",
        locale: "he-IL",
    },
    {
        country: "Jamaica",
        code: "JM",
        currency: "JMD",
        locale: "en-JM",
    },
    {
        country: "Jordan",
        code: "JO",
        currency: "JOD",
        locale: "en-JO",
    },
    {
        country: "Japan",
        code: "JP",
        currency: "JPY",
        locale: "ja-JP",
    },
    {
        country: "Kazakhstan",
        code: "KZ",
        currency: "KZT",
        locale: "en-KZ",
    },
    {
        country: "Kenya",
        code: "KE",
        currency: "KES",
        locale: "en-KE",
    },
    {
        country: "Kyrgyzstan",
        code: "KG",
        currency: "KGS",
        locale: "en-KG",
    },
    {
        country: "Cambodia",
        code: "KH",
        currency: "KHR",
        locale: "en-KH",
    },
    {
        country: "Korea, Republic of",
        code: "KR",
        currency: "KRW",
        locale: "ko-KR",
    },
    {
        country: "Kuwait",
        code: "KW",
        currency: "KWD",
        locale: "en-KW",
    },
    {
        country: "Lao People's Democratic Republic",
        code: "LA",
        currency: "LAK",
        locale: "en-LA",
    },
    {
        country: "Lebanon",
        code: "LB",
        currency: "LBP",
        locale: "en-LB",
    },
    {
        country: "Liberia",
        code: "LR",
        currency: "LRD",
        locale: "en-LR",
    },
    {
        country: "Libya",
        code: "LY",
        currency: "LYD",
        locale: "en-LY",
    },
    {
        country: "Sri Lanka",
        code: "LK",
        currency: "LKR",
        locale: "en-LK",
    },
    {
        country: "Lesotho",
        code: "LS",
        currency: "LSL",
        locale: "en-LS",
    },
    {
        country: "Macao",
        code: "MO",
        currency: "MOP",
        locale: "en-MO",
    },
    {
        country: "Morocco",
        code: "MA",
        currency: "MAD",
        locale: "en-MA",
    },
    {
        country: "Moldova, Republic of",
        code: "MD",
        currency: "MDL",
        locale: "en-MD",
    },
    {
        country: "Maldives",
        code: "MV",
        currency: "MVR",
        locale: "en-MV",
    },
    {
        country: "Mexico",
        code: "MX",
        currency: "MXN",
        locale: "es-MX",
    },
    {
        country: "North Macedonia",
        code: "MK",
        currency: "MKD",
        locale: "en-MK",
    },
    {
        country: "Myanmar",
        code: "MM",
        currency: "MMK",
        locale: "en-MM",
    },
    {
        country: "Mongolia",
        code: "MN",
        currency: "MNT",
        locale: "en-MN",
    },
    {
        country: "Mauritania",
        code: "MR",
        currency: "MRO",
        locale: "en-MR",
    },
    {
        country: "Mauritius",
        code: "MU",
        currency: "MUR",
        locale: "en-MU",
    },
    {
        country: "Malawi",
        code: "MW",
        currency: "MWK",
        locale: "en-MW",
    },
    {
        country: "Malaysia",
        code: "MY",
        currency: "MYR",
        locale: "ms-MY",
    },
    {
        country: "Namibia",
        code: "NA",
        currency: "NAD",
        locale: "en-NA",
    },
    {
        country: "Nigeria",
        code: "NG",
        currency: "NGN",
        locale: "en-NG",
    },
    {
        country: "Nicaragua",
        code: "NI",
        currency: "NIO",
        locale: "en-NI",
    },
    {
        country: "Norway",
        code: "NO",
        currency: "NOK",
        locale: "no-NO",
    },
    {
        country: "Nepal",
        code: "NP",
        currency: "NPR",
        locale: "en-NP",
    },
    {
        country: "New Zealand",
        code: "NZ",
        currency: "NZD",
        locale: "en-NZ",
    },
    {
        country: "Oman",
        code: "OM",
        currency: "OMR",
        locale: "en-OM",
    },
    {
        country: "Pakistan",
        code: "PK",
        currency: "PKR",
        locale: "en-PK",
    },
    {
        country: "Peru",
        code: "PE",
        currency: "PEN",
        locale: "en-PE",
    },
    {
        country: "Philippines",
        code: "PH",
        currency: "PHP",
        locale: "en-PH",
    },
    {
        country: "Papua New Guinea",
        code: "PG",
        currency: "PGK",
        locale: "en-PG",
    },
    {
        country: "Korea, Democratic People's Republic of",
        code: "KP",
        currency: "KPW",
        locale: "en-KP",
    },
    {
        country: "Paraguay",
        code: "PY",
        currency: "PYG",
        locale: "en-PY",
    },
    {
        country: "Qatar",
        code: "QA",
        currency: "QAR",
        locale: "en-QA",
    },
    {
        country: "Russian Federation",
        code: "RU",
        currency: "RUB",
        locale: "ru-RU",
    },
    {
        country: "Rwanda",
        code: "RW",
        currency: "RWF",
        locale: "en-RW",
    },
    {
        country: "Saudi Arabia",
        code: "SA",
        currency: "SAR",
        locale: "ar-SA",
    },
    {
        country: "Singapore",
        code: "SG",
        currency: "SGD",
        locale: "en-SG",
    },
    {
        country: "Saint Helena, Ascension and Tristan da Cunha",
        code: "SH",
        currency: "SHP",
        locale: "en-SH",
    },
    {
        country: "Solomon Islands",
        code: "SB",
        currency: "SBD",
        locale: "en-SB",
    },
    {
        country: "Sierra Leone",
        code: "SL",
        currency: "SLL",
        locale: "en-SL",
    },
    {
        country: "El Salvador",
        code: "SV",
        currency: "SVC",
        locale: "en-SV",
    },
    {
        country: "Somalia",
        code: "SO",
        currency: "SOS",
        locale: "en-SO",
    },
    {
        country: "South Sudan",
        code: "SS",
        currency: "SSP",
        locale: "en-SS",
    },
    {
        country: "Sao Tome and Principe",
        code: "ST",
        currency: "STD",
        locale: "en-ST",
    },
    {
        country: "Sweden",
        code: "SE",
        currency: "SEK",
        locale: "sv-SE",
    },
    {
        country: "Eswatini",
        code: "SZ",
        currency: "SZL",
        locale: "en-SZ",
    },
    {
        country: "Seychelles",
        code: "SC",
        currency: "SCR",
        locale: "en-SC",
    },
    {
        country: "Syrian Arab Republic",
        code: "SY",
        currency: "SYP",
        locale: "en-SY",
    },
    {
        country: "Thailand",
        code: "TH",
        currency: "THB",
        locale: "th-TH",
    },
    {
        country: "Tonga",
        code: "TO",
        currency: "TOP",
        locale: "en-TO",
    },
    {
        country: "Trinidad and Tobago",
        code: "TT",
        currency: "TTD",
        locale: "en-TT",
    },
    {
        country: "Tunisia",
        code: "TN",
        currency: "TND",
        locale: "en-TN",
    },
    {
        country: "Tanzania, United Republic of",
        code: "TZ",
        currency: "TZS",
        locale: "en-TZ",
    },
    {
        country: "Uganda",
        code: "UG",
        currency: "UGX",
        locale: "en-UG",
    },
    {
        country: "Uruguay",
        code: "UY",
        currency: "UYU",
        locale: "en-UY",
    },
    {
        country: "United States",
        code: "US",
        currency: "USD",
        locale: "en-US",
    },
    {
        country: "Uzbekistan",
        code: "UZ",
        currency: "UZS",
        locale: "en-UZ",
    },
    {
        country: "Viet Nam",
        code: "VN",
        currency: "VND",
        locale: "vi-VN",
    },
    {
        country: "Vanuatu",
        code: "VU",
        currency: "VUV",
        locale: "en-VU",
    },
    {
        country: "Samoa",
        code: "WS",
        currency: "WST",
        locale: "en-WS",
    },
    {
        country: "South Africa",
        code: "ZA",
        currency: "ZAR",
        locale: "en-ZA",
    },
];


function convertMyDollars(amount, currency) {
    const firstName = currency.split(" ").length > 0 ? currency.split(" ")[0] : currency;
    const currencyData  = countryCurrencyLocales?.find(data => (firstName.includes(data.country.split(" ").length > 0 ? data.country.split(" ")[0] : data.country) || firstName.startsWith(data.country.split(" ").length > 0 ? data.country.split(" ")[0] : data.country)));
    const currencyFormatter = new Intl.NumberFormat(`${currencyData.locale}`, {currency: currencyData.currency, style: "currency"}).format(amount);
    return currencyFormatter;
}